### ISSUE TITLE
Configurable User-Agent string

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#25] opened 2015-06-11 19:24 UTC
Client configuration should include option to set a User Agent string, which would provide indication the app that is making calls to the API. This should follow RFC 7231 Sec 5.5.3 http://tools.ietf.org/html/rfc7231#section-5.5.3. The app’s user agent should be prepended to a User-Agent string with “gedcomx-php/1.0 guzzle/{version} php/{version}”

**Comment by justincy** [comment] 2015-06-11 19:25
Isn't this a duplicate of #19?

**Comment by jimmyz** [comment] 2015-06-11 19:25
Just realized that and closed it.

From: Justin
Reply-To: FamilySearch/gedcomx-php
Date: Thursday, June 11, 2015 at 1:25 PM
To: FamilySearch/gedcomx-php
Cc: Jimmy Zimmerman
Subject: Re: [gedcomx-php] Configurable User-Agent string (#25)


Isn't this a duplicate of #19<https://github.com/FamilySearch/gedcomx-php/issues/19>?

**Closed by justincy** 2015-06-11 19:25 UTC
